#!../../../perl -w

#
# Purpose:
#	To demonstrate the Perl5 Cdk file selector widget.

#
# Load in the Cdk Extension.
#
use Cdk;
Cdk::init();

# Create the file selector.
my $fselect = new Cdk::Fselect ('Label' => "</B/16>Filename:", 
				'Dattrib' => "</B/5>",
				'Fattrib' => "</B/32>",
				'Lattrib' => "</B/33>",
				'Sattrib' => "</B/29>",
				'Filler' => "</B/24>_",
				'Height' => 20,
				'Width' => 50);

# Activate the object.
my $filename = $fselect->activate();

# Check the results.
if (! defined $filename)
{
   popupLabel (["<C>You hit escape. No file selected."]);
}
else
{
   popupLabel (["<C>You selected the following file", "<C>($filename)"]);
}

# Exit Cdk.
Cdk::end();
